name: All

on:
  push:
    paths-ignore:
      - '*.rst'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
        python: ['3.8', '3.9', '3.10']
    steps:

    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }} and PDM
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: pip install -v tox

    - name: Test with tox
      run: tox -v

    - name: Upload artifact for tags
      if: ${{ contains(matrix.os, 'ubuntu') && matrix.python == '3.8' }}
      uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: .tox/dist/*.whl
        if-no-files-found: error

  do_release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: wheel
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        draft: true
        files: |
          *.whl
