name: Build and test

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.git*'
      - '**.rst'
      - 'data_mining/**'
    tags:
      - 0.*
      - 1.*

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -v tox

      - name: Build sdist and wheel
        run: tox -e build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*
          if-no-files-found: error

  format:
    name: Formatting checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: isort formatting
        uses: isort/isort-action@master
        id: step_isort

      - name: black formatting
        if: success() || failure()
        uses: psf/black@stable
        id: step_black

      - name: Checkers don't affect workflow status
        if: >
          steps.step_isort.outcome == 'failure' ||
          steps.step_black.outcome == 'failure'
        run: exit 0

  test:
    name: Tox tests
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
        python: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Install dependencies
        run: pip install -v tox

      - name: Test wheel
        shell: bash # glob fails on Windows cmd
        run: tox --installpkg *.whl --result-json test-job-${{ strategy.job-index }}.json -v

      - name: Upload log
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: test-job-*.json
          if-no-files-found: error
