name: Publish release

on:
  workflow_run:
    workflows: ["Build and test"]
    types: [completed]
    branches:
      - 0.*
      - 1.*

jobs:
  github:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest
    steps:

    - name: Download artifact from previous workflow
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: dist
        path: dist
        check_artifacts: true

    - name: Publish draft GitHub release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        draft: true
        files: |
          dist/*.whl
          dist/*.tar.gz
