name: Testing

on:
  workflow_run:
    workflows: [Build and release]
    types: [completed]

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
        python: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: Download artifact from previous workflow
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: dist
        path: .
        check_artifacts: true

    - name: Install dependencies
      run: pip install -v tox

    - name: Test with wheel artifact
      shell: bash # glob fails on Windows cmd
      run: tox --installpkg *.whl --result-json test-job-${{ strategy.job-index }}.json -v

    - name: Upload log artifact
      uses: actions/upload-artifact@v3
      with:
        name: log
        path: test-job-*.json
        if-no-files-found: error
